remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Josemi's Github site
description: A place to share my notes
logo: /images/logo.png
