title: Josemi's Github site
logo: https://pbs.twimg.com/profile_images/378800000795058910/d611cb4aa977700fa86848cf0e27e004_400x400.jpeg  # /assets/img//logo.png
description: A place to share my notes
theme: jekyll-theme-minimal
google_analytics:
show_downloads: false
