theme: jekyll-theme-minimal # Esto es un comentario
title: marlucjo's Github site
logo: https://pbs.twimg.com/profile_images/378800000795058910/d611cb4aa977700fa86848cf0e27e004_400x400.jpeg  # /assets/img//logo.png
description: A place to share my notes
google_analytics:
show_downloads: false
